**Importing the dependencies**

In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

**Importing Models**

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

**Data Collection & Preprocessing**

In [9]:
# Loading Data into Pandas Dataframe
heart_disease_data = pd.read_csv('/content/heart_disease_data.csv')

In [10]:
# Printing 5 rows of Dataset:
heart_disease_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [11]:
# Shape of Dataset:
heart_disease_data.shape

(303, 14)

In [12]:
# Check for Null Values:
heart_disease_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [13]:
# Statistical Measures of Dataset:
heart_disease_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [14]:
# Distribution of Target Variable:
heart_disease_data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [15]:
# 1 --> Defective Heart
# 2 --> Healthy  Heart

**Splitting Features and Targets**

In [16]:
X = heart_disease_data.drop(columns= 'target', axis=1)
Y = heart_disease_data['target']

In [17]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [18]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

#**Train Test Split**

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=3)

In [20]:
print(X.shape,X_train.shape, X_test.shape)

(303, 13) (242, 13) (61, 13)

**Comparing the Performance of Differernt Models**

In [21]:
# List of Models:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [22]:
def compare_models_train_test():
  for model in models:
    # Training the model:
    model.fit(X_train, Y_train)
    # Evaluating the model:
    test_data_prediction = model.predict(X_test)
    accuracy = accuracy_score(Y_test, test_data_prediction)
    print("Accuracy Score of the Model", model, ' = ', accuracy)

In [23]:
compare_models_train_test()

Accuracy Score of the Model LogisticRegression(max_iter=1000)  =  0.7868852459016393
Accuracy Score of the Model SVC(kernel='linear')  =  0.7704918032786885
Accuracy Score of the Model KNeighborsClassifier()  =  0.6557377049180327
Accuracy Score of the Model RandomForestClassifier()  =  0.8032786885245902

#**Cross Validation**

In [26]:
cv_score_LR = cross_val_score(LogisticRegression(max_iter=1000),X,Y, cv=5)
print(cv_score_LR)

mean_accuracy_LR = sum(cv_score_LR)/len(cv_score_LR)
mean_accuracy_LR = mean_accuracy_LR*100
mean_accuracy_LR = round(mean_accuracy_LR,2)
print(mean_accuracy_LR)

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
82.83

**Support Vector Classifier**

In [29]:
cv_score_SVC = cross_val_score(SVC(kernel='linear'),X,Y, cv=5)
print(cv_score_SVC)
mean_accuracy_SVC = sum(cv_score_SVC)/len(cv_score_SVC)
mean_accuracy_SVC = mean_accuracy_SVC*100
mean_accuracy_SVC = round(mean_accuracy_SVC,2)
print(mean_accuracy_SVC)

[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
82.83

**RandomForestClassifier**

In [28]:
cv_score_RFC = cross_val_score(RandomForestClassifier(),X,Y, cv=5)
print(cv_score_RFC)
mean_accuracy_RFC = sum(cv_score_RFC)/len(cv_score_RFC)
mean_accuracy_RFC = mean_accuracy_RFC*100
mean_accuracy_RFC = round(mean_accuracy_RFC,2)
print(mean_accuracy_RFC)

[0.85245902 0.90163934 0.7704918  0.8        0.76666667]
81.83

**Creating a Function to compare the models:**

In [30]:
# List of Models:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [33]:
def compare_models_cross_validation():

  for model in models:

    cv_score = cross_val_score(model, X,Y, cv=5)
    mean_accuracy = sum(cv_score)/len(cv_score)
    mean_accuracy = mean_accuracy*100
    mean_accuracy = round(mean_accuracy,2)
    print("Cross Validation Accuracies for ", model, '=', cv_score)
    print('Accuracy % of the ', model, mean_accuracy)
    print('-----------------------------------------------')

In [34]:
compare_models_cross_validation()

Cross Validation Accuracies for  LogisticRegression(max_iter=1000) = [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
Accuracy % of the  LogisticRegression(max_iter=1000) 82.83
-----------------------------------------------
Cross Validation Accuracies for  SVC(kernel='linear') = [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
Accuracy % of the  SVC(kernel='linear') 82.83
-----------------------------------------------
Cross Validation Accuracies for  KNeighborsClassifier() = [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
Accuracy % of the  KNeighborsClassifier() 64.39
-----------------------------------------------
Cross Validation Accuracies for  RandomForestClassifier() = [0.81967213 0.8852459  0.80327869 0.81666667 0.8       ]
Accuracy % of the  RandomForestClassifier() 82.5
-----------------------------------------------